AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fase 2: Infraestrutura para site estático com container em EC2'

Resources:
  # Grupo de Segurança
  AcessoWebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite acesso HTTP publico na porta 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # O Servidor EC2
  ServidorWeb:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro # Instância elegível no AWS Academy
      # Pega a versão mais atualizada e segura do Amazon Linux 2023 automaticamente
      ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}'
      SecurityGroupIds:
        - !Ref AcessoWebSG
      
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y docker
          systemctl start docker
          systemctl enable docker
          docker run -d -p 80:80 nicollasfs/devops-pucrs-nicollas:latest

Outputs:
  URLdoSite:
    Description: 'Acessa o site em container por este link'
    # Retorna o DNS público gerado pela AWS para a sua máquina
    Value: !Sub 'http://${ServidorWeb.PublicDnsName}'