name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest # Sistema operacional
    steps:
      - uses: actions/checkout@v4 # Baixa o código
      - name: Executar Script
        run: echo "Configurado com sucesso!"
        
  validating-html:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: configurar node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: instalar HTMLHint
        run: npm install -g htmlhint
      - name: Validando htmlhin
        run: htmlhint index.html
  
  validating-prettier:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: configurar node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: instalar Prettier
        run: npm install -g prettier
      - name: Valindando Prettier
        run: prettier --check index.html
  
  validating-links:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: configurar node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: validando links
        uses: lycheeverse/lychee-action@v2
        with:
          args: index.html